apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slackerbot.fullname" . }}
data:
  OAUTH_CLIENT: {{ .Values.appConfig.oauthClientId | quote }}
  OAUTH_REDIRECT: https://{{ .Values.appConfig.hostname }}/oauth/redirect
  WEB_WHITELIST_GUILD_ID: {{ .Values.appConfig.oauthClientId | quote }}
