apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ include "slackerbot.fullname" . }}-db
spec:
  image: {{ .Values.database.image }}
  postgresVersion: {{ .Values.database.version }}
  port: 5432
  users:
    - name: {{ include "slackerbot.fullname" . }}
      databases:
        - {{ include "slackerbot.fullname" . }}
  instances:
    - dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.database.size }}
      name: main
      replicas: 1
  init:
    - name: init-script
      script:
        configMap:
          name: {{ include "slackerbot.fullname" . }}-db-init
          key: init.sql
  backups:
    pgbackrest:
      image: {{ .Values.database.backup.image }}
      configuration:
        - secret:
            name: {{ .Values.database.backup.s3secretName }}
      global:
        repo1-retention-full-type: time
        repo1-retention-full: "14"
        repo1-path: /{{ include "slackerbot.fullname" . }}
      repos:
        - name: repo1
          schedules:
            differential: 0 3 * * 1-6
            full: 0 3 * * 0
          s3:
            bucket: {{ .Values.database.backup.s3bucket }}
            endpoint: {{ .Values.database.backup.s3endpoint }}
            region: {{ .Values.database.backup.s3region }}