apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slackerbot.fullname" . }}-db-init
data:
  init.sql: |
    GRANT
    ALL
    PRIVILEGES
    ON
    SCHEMA
    public TO {{ include "slackerbot.fullname" . }};
    ALTER
    DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO {{ include "slackerbot.fullname" . }};