apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slackerbot.fullname" . }}
type: Opaque
data:
{{- $secretObj := lookup "v1" "Secret" .Release.Namespace ( include "slackerbot.fullname" . ) | default dict }}
{{- $dataObj := (get $secretObj "data") | default dict }}
{{- $chatgptToken := (get $dataObj "CHATGPT_TOKEN") | default ("" | b64enc) }}
  CHATGPT_TOKEN: {{ $chatgptToken | quote }}
{{- $discordToken := (get $dataObj "DISCORD_TOKEN") | default ("" | b64enc) }}
  DISCORD_TOKEN: {{ $discordToken | quote }}
{{- $oauthSecret := (get $dataObj "OAUTH_SECRET") | default ("" | b64enc) }}
  OAUTH_SECRET: {{ $oauthSecret | quote }}
{{- $jwtSecret := (get $dataObj "JWT_SECRET") | default (randAlphaNum 32 | b64enc) }}
  JWT_SECRET: {{ $jwtSecret | quote }}
